version: '3.1'

services:
  my-workout:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my-workout

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=my-workout

